#pragma once

namespace dicom {
namespace uids {
    // 
    extern const char*const VLImageStorageTrialRetired;
    extern const char*const VLMultiframeImageStorageTrialRetired;

    // Application Context Name
    extern const char*const DICOMApplicationContextName;

    // Application Hosting Model
    extern const char*const AbstractMultiDimensionalImageModel;
    extern const char*const NativeDICOMModel;

    // Coding Scheme
    extern const char*const DICOMControlledTerminology;

    // DICOM UIDs as a Coding Scheme
    extern const char*const DICOMUIDRegistry;

    // LDAP OID
    extern const char*const DicomAETitle;
    extern const char*const DicomApplicationCluster;
    extern const char*const DicomAssociationAcceptor;
    extern const char*const DicomAssociationInitiator;
    extern const char*const DicomAuthorizedNodeCertificateReference;
    extern const char*const DicomConfigurationRoot;
    extern const char*const DicomDescription;
    extern const char*const DicomDevice;
    extern const char*const DicomDeviceName;
    extern const char*const DicomDeviceSerialNumber;
    extern const char*const DicomDevicesRoot;
    extern const char*const DicomHostname;
    extern const char*const DicomInstalled;
    extern const char*const DicomInstitutionAddress;
    extern const char*const DicomInstitutionDepartmentName;
    extern const char*const DicomInstitutionName;
    extern const char*const DicomIssuerOfPatientID;
    extern const char*const DicomManufacturer;
    extern const char*const DicomManufacturerModelName;
    extern const char*const DicomNetworkAE;
    extern const char*const DicomNetworkConnection;
    extern const char*const DicomNetworkConnectionReference;
    extern const char*const DicomPort;
    extern const char*const DicomPreferredCalledAETitle;
    extern const char*const DicomPreferredCallingAETitle;
    extern const char*const DicomPrimaryDeviceType;
    extern const char*const DicomRelatedDeviceReference;
    extern const char*const DicomSoftwareVersion;
    extern const char*const DicomSOPClass;
    extern const char*const DicomStationName;
    extern const char*const DicomSupportedCharacterSet;
    extern const char*const DicomThisNodeCertificateReference;
    extern const char*const DicomTLSCyphersuite;
    extern const char*const DicomTransferCapability;
    extern const char*const DicomTransferRole;
    extern const char*const DicomTransferSyntax;
    extern const char*const DicomUniqueAETitle;
    extern const char*const DicomUniqueAETitlesRegistryRoot;
    extern const char*const DicomVendorData;

    // Meta SOP Class
    extern const char*const BasicColorPrintManagementMetaSOPClass;
    extern const char*const BasicGrayscalePrintManagementMetaSOPClass;
    extern const char*const DetachedPatientManagementMetaSOPClassRetired;
    extern const char*const DetachedResultsManagementMetaSOPClassRetired;
    extern const char*const DetachedStudyManagementMetaSOPClassRetired;
    extern const char*const GeneralPurposeWorklistManagementMetaSOPClass;
    extern const char*const PullStoredPrintManagementMetaSOPClassRetired;
    extern const char*const ReferencedColorPrintManagementMetaSOPClassRetired;
    extern const char*const ReferencedGrayscalePrintManagementMetaSOPClassRetired;

    // Query/Retrieve
    extern const char*const ColorPaletteInformationModelFIND;
    extern const char*const ColorPaletteInformationModelGET;
    extern const char*const ColorPaletteInformationModelMOVE;

    // Service Class
    extern const char*const StorageServiceClass;
    extern const char*const UnifiedWorklistAndProcedureStepServiceClass;
    extern const char*const UnifiedWorklistAndProcedureStepServiceClassTrialRetired;

    // SOP Class
    extern const char*const TwelveLeadECGWaveformStorage;
    extern const char*const AmbulatoryECGWaveformStorage;
    extern const char*const ArterialPulseWaveformStorage;
    extern const char*const AudioSRStorageTrialRetired;
    extern const char*const AutorefractionMeasurementsStorage;
    extern const char*const BasicAnnotationBoxSOPClass;
    extern const char*const BasicColorImageBoxSOPClass;
    extern const char*const BasicFilmBoxSOPClass;
    extern const char*const BasicFilmSessionSOPClass;
    extern const char*const BasicGrayscaleImageBoxSOPClass;
    extern const char*const BasicPrintImageOverlayBoxSOPClassRetired;
    extern const char*const BasicStructuredDisplayStorage;
    extern const char*const BasicStudyContentNotificationSOPClassRetired;
    extern const char*const BasicTextSRStorage;
    extern const char*const BasicVoiceAudioWaveformStorage;
    extern const char*const BlendingSoftcopyPresentationStateStorageSOPClass;
    extern const char*const BreastImagingRelevantPatientInformationQuery;
    extern const char*const BreastTomosynthesisImageStorage;
    extern const char*const CardiacElectrophysiologyWaveformStorage;
    extern const char*const CardiacRelevantPatientInformationQuery;
    extern const char*const ChestCADSRStorage;
    extern const char*const ColonCADSRStorage;
    extern const char*const ColorSoftcopyPresentationStateStorageSOPClass;
    extern const char*const CompositeInstanceRetrieveWithoutBulkDataGET;
    extern const char*const CompositeInstanceRootRetrieveGET;
    extern const char*const CompositeInstanceRootRetrieveMOVE;
    extern const char*const ComprehensiveSRStorage;
    extern const char*const ComprehensiveSRStorageTrialRetired;
    extern const char*const ComputedRadiographyImageStorage;
    extern const char*const CTImageStorage;
    extern const char*const DeformableSpatialRegistrationStorage;
    extern const char*const DetachedInterpretationManagementSOPClassRetired;
    extern const char*const DetachedPatientManagementSOPClassRetired;
    extern const char*const DetachedResultsManagementSOPClassRetired;
    extern const char*const DetachedStudyManagementSOPClassRetired;
    extern const char*const DetachedVisitManagementSOPClassRetired;
    extern const char*const DetailSRStorageTrialRetired;
    extern const char*const DICOSCTImageStorage;
    extern const char*const DICOSDigitalXRayImageStorageForPresentation;
    extern const char*const DICOSDigitalXRayImageStorageForProcessing;
    extern const char*const DICOSThreatDetectionReportStorage;
    extern const char*const DigitalIntraoralXRayImageStorageForPresentation;
    extern const char*const DigitalIntraoralXRayImageStorageForProcessing;
    extern const char*const DigitalMammographyXRayImageStorageForPresentation;
    extern const char*const DigitalMammographyXRayImageStorageForProcessing;
    extern const char*const DigitalXRayImageStorageForPresentation;
    extern const char*const DigitalXRayImageStorageForProcessing;
    extern const char*const EddyCurrentImageStorage;
    extern const char*const EddyCurrentMultiframeImageStorage;
    extern const char*const EncapsulatedCDAStorage;
    extern const char*const EncapsulatedPDFStorage;
    extern const char*const EnhancedCTImageStorage;
    extern const char*const EnhancedMRColorImageStorage;
    extern const char*const EnhancedMRImageStorage;
    extern const char*const EnhancedPETImageStorage;
    extern const char*const EnhancedSRStorage;
    extern const char*const EnhancedUSVolumeStorage;
    extern const char*const EnhancedXAImageStorage;
    extern const char*const EnhancedXRFImageStorage;
    extern const char*const GeneralAudioWaveformStorage;
    extern const char*const GeneralECGWaveformStorage;
    extern const char*const GeneralPurposePerformedProcedureStepSOPClass;
    extern const char*const GeneralPurposeScheduledProcedureStepSOPClass;
    extern const char*const GeneralPurposeWorklistInformationModelFIND;
    extern const char*const GeneralRelevantPatientInformationQuery;
    extern const char*const GenericImplantTemplateInformationModelFIND;
    extern const char*const GenericImplantTemplateInformationModelGET;
    extern const char*const GenericImplantTemplateInformationModelMOVE;
    extern const char*const GenericImplantTemplateStorage;
    extern const char*const GrayscaleSoftcopyPresentationStateStorageSOPClass;
    extern const char*const HangingProtocolInformationModelFIND;
    extern const char*const HangingProtocolInformationModelGET;
    extern const char*const HangingProtocolInformationModelMOVE;
    extern const char*const HangingProtocolStorage;
    extern const char*const HardcopyColorImageStorageSOPClassRetired;
    extern const char*const HardcopyGrayscaleImageStorageSOPClassRetired;
    extern const char*const HemodynamicWaveformStorage;
    extern const char*const ImageOverlayBoxSOPClassRetired;
    extern const char*const ImplantAssemblyTemplateInformationModelFIND;
    extern const char*const ImplantAssemblyTemplateInformationModelGET;
    extern const char*const ImplantAssemblyTemplateInformationModelMOVE;
    extern const char*const ImplantAssemblyTemplateStorage;
    extern const char*const ImplantTemplateGroupInformationModelFIND;
    extern const char*const ImplantTemplateGroupInformationModelGET;
    extern const char*const ImplantTemplateGroupInformationModelMOVE;
    extern const char*const ImplantTemplateGroupStorage;
    extern const char*const ImplantationPlanSRStorage;
    extern const char*const InstanceAvailabilityNotificationSOPClass;
    extern const char*const IntraocularLensCalculationsStorage;
    extern const char*const IntravascularOpticalCoherenceTomographyImageStorageForPresentation;
    extern const char*const IntravascularOpticalCoherenceTomographyImageStorageForProcessing;
    extern const char*const KeratometryMeasurementsStorage;
    extern const char*const KeyObjectSelectionDocumentStorage;
    extern const char*const LensometryMeasurementsStorage;
    extern const char*const MacularGridThicknessAndVolumeReportStorage;
    extern const char*const MammographyCADSRStorage;
    extern const char*const MediaCreationManagementSOPClassUID;
    extern const char*const MediaStorageDirectoryStorage;
    extern const char*const ModalityPerformedProcedureStepNotificationSOPClass;
    extern const char*const ModalityPerformedProcedureStepRetrieveSOPClass;
    extern const char*const ModalityPerformedProcedureStepSOPClass;
    extern const char*const ModalityWorklistInformationModelFIND;
    extern const char*const MRImageStorage;
    extern const char*const MRSpectroscopyStorage;
    extern const char*const MultiframeGrayscaleByteSecondaryCaptureImageStorage;
    extern const char*const MultiframeGrayscaleWordSecondaryCaptureImageStorage;
    extern const char*const MultiframeSingleBitSecondaryCaptureImageStorage;
    extern const char*const MultiframeTrueColorSecondaryCaptureImageStorage;
    extern const char*const NuclearMedicineImageStorage;
    extern const char*const NuclearMedicineImageStorageRetired;
    extern const char*const OphthalmicAxialMeasurementsStorage;
    extern const char*const OphthalmicPhotography16BitImageStorage;
    extern const char*const OphthalmicPhotography8BitImageStorage;
    extern const char*const OphthalmicTomographyImageStorage;
    extern const char*const OphthalmicVisualFieldStaticPerimetryMeasurementsStorage;
    extern const char*const PatientRootQueryRetrieveInformationModelFIND;
    extern const char*const PatientRootQueryRetrieveInformationModelGET;
    extern const char*const PatientRootQueryRetrieveInformationModelMOVE;
    extern const char*const PatientStudyOnlyQueryRetrieveInformationModelFINDRetired;
    extern const char*const PatientStudyOnlyQueryRetrieveInformationModelGETRetired;
    extern const char*const PatientStudyOnlyQueryRetrieveInformationModelMOVERetired;
    extern const char*const PositronEmissionTomographyImageStorage;
    extern const char*const PresentationLUTSOPClass;
    extern const char*const PrintJobSOPClass;
    extern const char*const PrintQueueManagementSOPClassRetired;
    extern const char*const PrinterConfigurationRetrievalSOPClass;
    extern const char*const PrinterSOPClass;
    extern const char*const ProceduralEventLoggingSOPClass;
    extern const char*const ProcedureLogStorage;
    extern const char*const ProductCharacteristicsQuerySOPClass;
    extern const char*const PseudoColorSoftcopyPresentationStateStorageSOPClass;
    extern const char*const PullPrintRequestSOPClassRetired;
    extern const char*const RawDataStorage;
    extern const char*const RealWorldValueMappingStorage;
    extern const char*const ReferencedImageBoxSOPClassRetired;
    extern const char*const RespiratoryWaveformStorage;
    extern const char*const RTBeamsDeliveryInstructionStorage;
    extern const char*const RTBeamsDeliveryInstructionStorageTrialRetired;
    extern const char*const RTBeamsTreatmentRecordStorage;
    extern const char*const RTBrachyTreatmentRecordStorage;
    extern const char*const RTConventionalMachineVerification;
    extern const char*const RTConventionalMachineVerificationTrialRetired;
    extern const char*const RTDoseStorage;
    extern const char*const RTImageStorage;
    extern const char*const RTIonBeamsTreatmentRecordStorage;
    extern const char*const RTIonMachineVerification;
    extern const char*const RTIonMachineVerificationTrialRetired;
    extern const char*const RTIonPlanStorage;
    extern const char*const RTPlanStorage;
    extern const char*const RTStructureSetStorage;
    extern const char*const RTTreatmentSummaryRecordStorage;
    extern const char*const SecondaryCaptureImageStorage;
    extern const char*const SegmentationStorage;
    extern const char*const SpatialFiducialsStorage;
    extern const char*const SpatialRegistrationStorage;
    extern const char*const SpectaclePrescriptionReportStorage;
    extern const char*const StandaloneCurveStorageRetired;
    extern const char*const StandaloneModalityLUTStorageRetired;
    extern const char*const StandaloneOverlayStorageRetired;
    extern const char*const StandalonePETCurveStorageRetired;
    extern const char*const StandaloneVOILUTStorageRetired;
    extern const char*const StereometricRelationshipStorage;
    extern const char*const StorageCommitmentPullModelSOPClassRetired;
    extern const char*const StorageCommitmentPushModelSOPClass;
    extern const char*const StoredPrintStorageSOPClassRetired;
    extern const char*const StudyComponentManagementSOPClassRetired;
    extern const char*const StudyRootQueryRetrieveInformationModelFIND;
    extern const char*const StudyRootQueryRetrieveInformationModelGET;
    extern const char*const StudyRootQueryRetrieveInformationModelMOVE;
    extern const char*const SubjectiveRefractionMeasurementsStorage;
    extern const char*const SubstanceAdministrationLoggingSOPClass;
    extern const char*const SubstanceApprovalQuerySOPClass;
    extern const char*const SurfaceSegmentationStorage;
    extern const char*const TextSRStorageTrialRetired;
    extern const char*const UltrasoundImageStorage;
    extern const char*const UltrasoundImageStorageRetired;
    extern const char*const UltrasoundMultiframeImageStorage;
    extern const char*const UltrasoundMultiframeImageStorageRetired;
    extern const char*const UnifiedProcedureStepEventSOPClass;
    extern const char*const UnifiedProcedureStepEventSOPClassTrialRetired;
    extern const char*const UnifiedProcedureStepPullSOPClass;
    extern const char*const UnifiedProcedureStepPullSOPClassTrialRetired;
    extern const char*const UnifiedProcedureStepPushSOPClass;
    extern const char*const UnifiedProcedureStepPushSOPClassTrialRetired;
    extern const char*const UnifiedProcedureStepWatchSOPClass;
    extern const char*const UnifiedProcedureStepWatchSOPClassTrialRetired;
    extern const char*const VerificationSOPClass;
    extern const char*const VideoEndoscopicImageStorage;
    extern const char*const VideoMicroscopicImageStorage;
    extern const char*const VideoPhotographicImageStorage;
    extern const char*const VisualAcuityMeasurementsStorage;
    extern const char*const VLEndoscopicImageStorage;
    extern const char*const VLMicroscopicImageStorage;
    extern const char*const VLPhotographicImageStorage;
    extern const char*const VLSlideCoordinatesMicroscopicImageStorage;
    extern const char*const VLWholeSlideMicroscopyImageStorage;
    extern const char*const VOILUTBoxSOPClass;
    extern const char*const WaveformStorageTrialRetired;
    extern const char*const XAXRFGrayscaleSoftcopyPresentationStateStorage;
    extern const char*const XRay3DAngiographicImageStorage;
    extern const char*const XRay3DCraniofacialImageStorage;
    extern const char*const XRayAngiographicBiPlaneImageStorageRetired;
    extern const char*const XRayAngiographicImageStorage;
    extern const char*const XRayRadiationDoseSRStorage;
    extern const char*const XRayRadiofluoroscopicImageStorage;

    // Synchronization Frame of Reference
    extern const char*const UniversalCoordinatedTime;

    // Transfer
    extern const char*const ColorPaletteStorage;

    // Transfer Syntax
    extern const char*const DeflatedExplicitVRLittleEndian;
    extern const char*const ExplicitVRBigEndian;
    extern const char*const ExplicitVRLittleEndian;
    extern const char*const ImplicitVRLittleEndian;
    extern const char*const JPEG2000ImageCompression;
    extern const char*const JPEG2000ImageCompressionLosslessOnly;
    extern const char*const JPEG2000Part2MulticomponentImageCompression;
    extern const char*const JPEG2000Part2MulticomponentImageCompressionLosslessOnly;
    extern const char*const JPEGBaselineProcess1;
    extern const char*const JPEGExtendedProcess24;
    extern const char*const JPEGExtendedProcess35Retired;
    extern const char*const JPEGExtendedHierarchicalProcess1618Retired;
    extern const char*const JPEGExtendedHierarchicalProcess1719Retired;
    extern const char*const JPEGFullProgressionHierarchicalProcess2426Retired;
    extern const char*const JPEGFullProgressionHierarchicalProcess2527Retired;
    extern const char*const JPEGFullProgressionNonHierarchicalProcess1012Retired;
    extern const char*const JPEGFullProgressionNonHierarchicalProcess1113Retired;
    extern const char*const JPEGLosslessHierarchicalProcess28Retired;
    extern const char*const JPEGLosslessHierarchicalProcess29Retired;
    extern const char*const JPEGLosslessNonHierarchicalProcess14;
    extern const char*const JPEGLosslessNonHierarchicalProcess15Retired;
    extern const char*const JPEGLosslessNonHierarchicalFirstOrderPredictionProcess14SelectionValue1;
    extern const char*const JPEGSpectralSelectionHierarchicalProcess2022Retired;
    extern const char*const JPEGSpectralSelectionHierarchicalProcess2123Retired;
    extern const char*const JPEGSpectralSelectionNonHierarchicalProcess68Retired;
    extern const char*const JPEGSpectralSelectionNonHierarchicalProcess79Retired;
    extern const char*const JPEGLSLosslessImageCompression;
    extern const char*const JPEGLSLossyNearLosslessImageCompression;
    extern const char*const JPIPReferenced;
    extern const char*const JPIPReferencedDeflate;
    extern const char*const MPEG2MainProfileHighLevel;
    extern const char*const MPEG2MainProfileMainLevel;
    extern const char*const MPEG4AVCH264BDcompatibleHighProfileLevel41;
    extern const char*const MPEG4AVCH264HighProfileLevel41;
    extern const char*const RFC2557MIMEEncapsulation;
    extern const char*const RLELossless;
    extern const char*const XMLEncoding;

    // Well-known frame of reference
    extern const char*const ICBM452T1FrameOfReference;
    extern const char*const ICBMSingleSubjectMRIFrameOfReference;
    extern const char*const SPM2AVG152PDFrameOfReference;
    extern const char*const SPM2AVG152T1FrameOfReference;
    extern const char*const SPM2AVG152T2FrameOfReference;
    extern const char*const SPM2AVG305T1FrameOfReference;
    extern const char*const SPM2BRAINMASKFrameOfReference;
    extern const char*const SPM2CSFFrameOfReference;
    extern const char*const SPM2EPIFrameOfReference;
    extern const char*const SPM2FILT1FrameOfReference;
    extern const char*const SPM2GRAYFrameOfReference;
    extern const char*const SPM2PDFrameOfReference;
    extern const char*const SPM2PETFrameOfReference;
    extern const char*const SPM2SINGLESUBJT1FrameOfReference;
    extern const char*const SPM2SPECTFrameOfReference;
    extern const char*const SPM2T1FrameOfReference;
    extern const char*const SPM2T2FrameOfReference;
    extern const char*const SPM2TRANSMFrameOfReference;
    extern const char*const SPM2WHITEFrameOfReference;
    extern const char*const TalairachBrainAtlasFrameOfReference;

    // Well-known Print Queue SOP Instance
    extern const char*const PrintQueueSOPInstanceRetired;

    // Well-known Printer SOP Instance
    extern const char*const PrinterConfigurationRetrievalSOPInstance;
    extern const char*const PrinterSOPInstance;

    // Well-known SOP Instance
    extern const char*const HotIronColorPaletteSOPInstance;
    extern const char*const HotMetalBlueColorPaletteSOPInstance;
    extern const char*const PET20StepColorPaletteSOPInstance;
    extern const char*const PETColorPaletteSOPInstance;
    extern const char*const ProceduralEventLoggingSOPInstance;
    extern const char*const StorageCommitmentPullModelSOPInstanceRetired;
    extern const char*const StorageCommitmentPushModelSOPInstance;
    extern const char*const SubstanceAdministrationLoggingSOPInstance;
    extern const char*const UnifiedWorklistAndProcedureStepSOPInstance;
} // namespace uids
}
